[project]
name = "wsdl-classes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "pip>=25.3",
    "rdflib>=7.5.0",
]
